server:
  port: 8086
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    data-username: TEST1
    data-password: 12345
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
logging:
  level:
    root: info
  file: spring-boot-logger/island-asset